# Generated by Django 4.2.2 on 2023-12-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name_white', models.CharField(max_length=100)),
                ('player_name_black', models.CharField(max_length=100)),
                ('moves', models.JSONField()),
                ('date', models.DateField()),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
