# Generated by Django 4.2.2 on 2023-07-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price_in_usd',
        ),
    ]
